# Generated by Django 3.2.5 on 2021-08-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('slippers', 'Шлёпанцы'), ('sabo', 'Сабо'), ('homeslips', 'Домашки'), ('sandals', 'Сандалии')], default='slippers', max_length=20, verbose_name='Категории'),
        ),
    ]
